export interface Product {
	id: string;
	name: string;
	category: string;
	image: string;
	price: number;
	description: string;
	contents: string[];
}

export interface Category {
	id: string;
	name: string;
	slug: string;
	description: string;
	image: string;
	color: string;
}

export const CATEGORIES: Category[] = [
	{
		id: '1',
		name: 'Breakfast Menu',
		slug: 'breakfast-menu',
		description: 'Start your day with our delicious breakfast selections',
		image: '/images/pap-akara.png',
		color: 'from-pink-500 to-rose-500',
	},
	{
		id: '2',
		name: 'Rice & Beans',
		slug: 'rice-and-beans',
		description: 'Premium varieties of rice from around the world',
		image: '/images/rice.png',
		color: 'from-amber-500 to-orange-500',
	},
	{
		id: '3',
		name: 'Swallow',
		slug: 'swallow',
		description: 'Traditional swallow dishes - smooth, creamy, and satisfying',
		image: '/images/african-swallow.png',
		color: 'from-yellow-500 to-amber-600',
	},
	{
		id: '4',
		name: 'Soups',
		slug: 'soups',
		description: 'Hearty and flavorful soups - perfect for any occasion',
		image: '/images/nigerian-soup.png',
		color: 'from-red-500 to-rose-600',
	},
	{
		id: '5',
		name: 'Proteins',
		slug: 'proteins',
		description:
			'Premium selection of proteins - grilled, fried, and seasoned to perfection',
		image: '/images/chicken.webp',
		color: 'from-orange-500 to-red-600',
	},
	{
		id: '6',
		name: 'Small Chops & Sides',
		slug: 'small-chops-sides',
		description: 'Delicious small chops and sides to complement your meal',
		image: '/images/side-dish.jpg',
		color: 'from-green-500 to-emerald-600',
	},
	{
		id: '7',
		name: 'Pasta',
		slug: 'pasta',
		description: 'Delicious pasta dishes with rich sauces and proteins',
		image: '/images/pasta.jpg',
		color: 'from-yellow-600 to-orange-500',
	},
	{
		id: '8',
		name: 'Combo Menu',
		slug: 'combo-menu',
		description:
			'Complete meal combinations - everything you need in one plate',
		image: '/images/jollof-rice-and-chicken.webp',
		color: 'from-purple-500 to-violet-600',
	},
	{
		id: '9',
		name: 'Drinks',
		slug: 'drinks',
		description: 'Refreshing beverages to complement your meal',
		image: '/images/drinks.jpg',
		color: 'from-blue-500 to-cyan-500',
	},
	{
		id: '10',
		name: 'Fast Food',
		slug: 'fast-food',
		description: 'Quick and delicious fast food favorites',
		image: '/images/fast-food.jpg',
		color: 'from-red-500 to-orange-500',
	},
];

export const PRODUCTS: Product[] = [
	// Rice & Beans
	{
		id: 'rice-1',
		name: 'Jollof Rice',
		category: 'rice-and-beans',
		image: '/images/jollof-rice.jpg',
		price: 2500,
		description:
			'Traditional West African rice cooked in a rich tomato and spice blend, offering a comforting taste of home.',
		contents: [
			'A serving of seasoned african jollof rice with mixed vegetables, best enjoyed with tender beef or fried chicken (sold separately).',
		],
	},
	{
		id: 'rice-2',
		name: 'Fried Rice',
		category: 'rice-and-beans',
		image: '/images/Fried-Rice.jpg',
		price: 2000,
		description:
			'Fragrant and fluffy rice stir-fried with a colorful mix of vegetables and tender meat for a satisfying meal.',
		contents: [
			'A portion of golden fried rice with green peas, carrots, sweet corn, and choice of beef or liver, cooked to perfection.',
		],
	},
	{
		id: 'rice-3',
		name: 'White Rice',
		category: 'rice-and-beans',
		image: '/images/white-rice.jpg',
		price: 1500,
		description:
			'Perfectly cooked white rice served simply with rich stew for a classic, comforting meal.',
		contents: [
			'A plate of steamed white rice with savory stew, tender beef, and optional fried plantain (Sold Separately) for extra flavor.',
		],
	},
	{
		id: 'rice-4',
		name: 'Rice & Stew',
		category: 'rice-and-beans',
		image: '/images/white-rice-and-stew.png',
		price: 3000,
		description: 'White rice with rich tomato stew',
		contents: ['White Rice', 'Tomato Stew', 'Beef', 'Fish', 'Plantain'],
	},
	{
		id: 'rice-5',
		name: 'Banga Rice',
		category: 'rice-and-beans',
		image: '/images/banga-rice.jfif',
		price: 3000,
		description: 'Rice cooked in rich palm nut sauce',
		contents: [
			'Banga Rice',
			'Beef',
			'Fish',
			'Dried Fish',
			'Beletete (Banga spice)',
		],
	},
	{
		id: 'rice-6',
		name: 'Coconut Rice',
		category: 'rice-and-beans',
		image: '/images/Creamy-Coconut-Rice.jpeg',
		price: 3000,
		description: 'Rice cooked in rich coconut milk',
		contents: ['Coconut Rice', 'Shrimp', 'Chicken', 'Carrots', 'Green Peas'],
	},
	{
		id: 'rice-7',
		name: 'Jollof Rice & Chicken',
		category: 'rice-and-beans',
		image: '/images/jollof-rice-and-chicken.webp',
		price: 4500,
		description: 'Jollof rice served with grilled chicken',
		contents: [
			'Jollof Rice',
			'Grilled Chicken (whole)',
			'Cabbage',
			'Carrots',
			'Plantain',
		],
	},
	{
		id: 'rice-8',
		name: 'Fried Rice & Chicken',
		category: 'rice-and-beans',
		image: '/images/fried-rice-chicken.jpg',
		price: 4200,
		description: 'Fried rice served with grilled chicken',
		contents: ['Fried Rice', 'Grilled Chicken (whole)', 'Coleslaw', 'Plantain'],
	},
	{
		id: 'beans-1',
		name: 'Palm Oil Beans',
		category: 'rice-and-beans',
		image: '/images/beans.png',
		price: 1200,
		description: 'Cooked beans with seasoning',
		contents: ['Honey Beans', 'Palm Oil', 'Pepper', 'Onions', 'Crayfish'],
	},
	{
		id: 'beans-2',
		name: 'Fried Beans',
		category: 'rice-and-beans',
		image: '/images/fried-beans.png',
		price: 1500,
		description: 'Fried beans with spices and seasoning',
		contents: ['Honey Beans', 'Fried Plantain', 'Pepper Sauce', 'Onions'],
	},
	{
		id: 'beans-3',
		name: 'Beans & Plantain',
		category: 'rice-and-beans',
		image: '/images/beans-plantain.jpg',
		price: 2500,
		description: 'Fried beans served with ripe plantain',
		contents: ['Fried Beans', 'Ripe Plantain', 'Fish', 'Pepper Sauce'],
	},
	{
		id: 'beans-4',
		name: 'Beans Porridge',
		category: 'rice-and-beans',
		image: '/images/beans-porridge.jpg',
		price: 2000,
		description: 'Creamy beans porridge with spices',
		contents: ['Honey Beans', 'Palm Oil', 'Plantain', 'Fish', 'Yam (optional)'],
	},

	// Swallow
	{
		id: 'swallow-1',
		name: 'Eba (Garri)',
		category: 'swallow',
		image: '/images/eba.jpg',
		price: 1500,
		description: 'Smooth Eba, perfect for dipping in soups',
		contents: [
			'Eba (Cassava flakes)',
			'Your choice of soup (ordered separately)',
		],
	},
	{
		id: 'swallow-2',
		name: 'Starch',
		category: 'swallow',
		image: '/images/starch.jpg',
		price: 1800,
		description: 'Smooth and stretchy starch swallow, perfect for Banga soup',
		contents: [
			'Starch (Cassava starch)',
			'Your choice of soup (ordered separately)',
		],
	},
	{
		id: 'swallow-3',
		name: 'Fufu',
		category: 'swallow',
		image: '/images/fufu.jpg',
		price: 2500,
		description:
			'Made from fermented cassava, fufu is smooth and slightly tangy',
		contents: [
			'Fufu (Fermented Cassava)',
			'Your choice of soup (ordered separately)',
		],
	},
	{
		id: 'swallow-4',
		name: 'Poundo',
		category: 'swallow',
		image: '/images/poundo-pounded-yam.png',
		price: 3000,
		description: 'Made from yam flour with a smooth, stretchy texture',
		contents: ['Pounded Yam flour', 'Your choice of soup (ordered separately)'],
	},
	{
		id: 'swallow-5',
		name: 'Wheat',
		category: 'swallow',
		image: '/images/wheat.jpg',
		price: 3000,
		description: 'Smooth texture and mild flavor, high in fiber',
		contents: ['Wheat flour', 'Your choice of soup (ordered separately)'],
	},
	{
		id: 'swallow-6',
		name: 'Amala',
		category: 'swallow',
		image: '/images/amala.jpg',
		price: 2000,
		description: 'Smooth yam flour swallow, perfect with ewedu soup',
		contents: ['Amala (Yam flour)', 'Your choice of soup (ordered separately)'],
	},
	{
		id: 'swallow-7',
		name: 'Semovita',
		category: 'swallow',
		image: '/images/semovita.jpg',
		price: 1800,
		description: 'Smooth semolina swallow',
		contents: ['Semolina flour', 'Your choice of soup (ordered separately)'],
	},

	// Soups
	{
		id: 'soup-1',
		name: 'Egusi Soup',
		category: 'soups',
		image: '/images/egusi-soup.png',
		price: 3500,
		description: 'Rich and creamy melon soup',
		contents: [
			'Ground Egusi (Melon)',
			'Vegetables (Ugu)',
			'Stockfish',
			'Beef',
			'Pomo',
			'Crayfish',
		],
	},
	{
		id: 'soup-2',
		name: 'Banga Soup',
		category: 'soups',
		image: '/images/banga-stew-ofe-akwu-soup.png',
		price: 2800,
		description: 'Rich palm nut soup',
		contents: [
			'Palm Nut Extract',
			'Beef',
			'Fish',
			'Dried Fish',
			'Bangalore spice mix',
			'Beletete',
		],
	},
	{
		id: 'soup-3',
		name: 'Owo Soup',
		category: 'soups',
		image: '/images/owo.jpg',
		price: 2800,
		description: 'Smooth and rich traditional soup',
		contents: [
			'Owo (Beans flour)',
			'Palm Oil',
			'Beef',
			'Fish',
			'Crayfish',
			'Pepper',
		],
	},
	{
		id: 'soup-4',
		name: 'Egusi Peppersoup',
		category: 'soups',
		image: '/images/egusi-pepper-soup.jpeg',
		price: 2800,
		description: 'Spicy melon soup',
		contents: [
			'Ground Egusi',
			'Peppersoup spice',
			'Beef',
			'Fish',
			'Scent leaf',
		],
	},
	{
		id: 'soup-5',
		name: 'Okro Soup',
		category: 'soups',
		image: '/images/okra-soup.png',
		price: 2800,
		description: 'Smooth okra soup with rich stock',
		contents: [
			'Fresh Okro',
			'Palm Oil',
			'Beef',
			'Fish',
			'Stockfish',
			'Crayfish',
			'Ugu leaves',
		],
	},
	{
		id: 'soup-6',
		name: 'Vegetable Soup',
		category: 'soups',
		image: '/images/vegetable-soup.png',
		price: 2500,
		description: 'Fresh vegetables in savory broth',
		contents: [
			'Ugu leaves',
			'Water leaves',
			'Beef',
			'Fish',
			'Stockfish',
			'Crayfish',
		],
	},
	{
		id: 'soup-7',
		name: 'Pepper Soup',
		category: 'soups',
		image: '/images/PepperSoup.png',
		price: 2200,
		description: 'Spicy pepper soup with meat',
		contents: [
			'Peppersoup spice',
			'Beef/Catfish/Chicken',
			'Scent leaf',
			'Scotch bonnet',
			'Onions',
		],
	},
	{
		id: 'soup-8',
		name: 'Ewedu Soup',
		category: 'soups',
		image: '/images/ewedu.jpg',
		price: 2000,
		description: 'Smooth jute leaves soup, perfect with amala',
		contents: [
			'Ewedu leaves',
			'Locust bean (Iru)',
			'Crayfish',
			'Beef (optional)',
			'Stock',
		],
	},
	{
		id: 'soup-9',
		name: 'Ogbono Soup',
		category: 'soups',
		image: '/images/ogbono.jpg',
		price: 3200,
		description: 'Rich and drawy wild mango seed soup',
		contents: [
			'Ground Ogbono',
			'Palm Oil',
			'Beef',
			'Stockfish',
			'Dried Fish',
			'Ugu leaves',
			'Crayfish',
		],
	},
	{
		id: 'soup-10',
		name: 'Afang Soup',
		category: 'soups',
		image: '/images/afang.jpg',
		price: 3500,
		description: 'Rich vegetable soup from the Efik people',
		contents: [
			'Afang leaves',
			'Water leaves',
			'Beef',
			'Stockfish',
			'Kanda',
			'Periwinkle',
			'Crayfish',
			'Palm Oil',
		],
	},
	{
		id: 'soup-11',
		name: 'Edikang Ikong',
		category: 'soups',
		image: '/images/edikang-ikong.jpg',
		price: 3800,
		description: 'Nutritious vegetable soup with assorted meat',
		contents: [
			'Ugu leaves',
			'Water leaves',
			'Beef',
			'Stockfish',
			'Kanda',
			'Periwinkle',
			'Crayfish',
			'Palm Oil',
		],
	},

	// Proteins
	{
		id: 'protein-1',
		name: 'Grilled Chicken',
		category: 'proteins',
		image: '/images/grilled-chicken.png',
		price: 4500,
		description: 'Perfectly grilled chicken with spices',
		contents: ['Whole Grilled Chicken', 'Pepper Sauce', 'Onions', 'Spice rub'],
	},
	{
		id: 'protein-2',
		name: 'Fried Fish',
		category: 'proteins',
		image: '/images/fried-fish.png',
		price: 5000,
		description: 'Crispy golden fried fish',
		contents: ['Whole Tilapia/Croaker', 'Pepper Sauce', 'Onions', 'Cabbage'],
	},
	{
		id: 'protein-3',
		name: 'Beef Steak',
		category: 'proteins',
		image: '/images/beef-steak.png',
		price: 5500,
		description: 'Tender beef steak cooked to perfection',
		contents: [
			'Beef Steak (300g)',
			'Pepper Sauce',
			'Onions',
			'Grilled vegetables',
		],
	},
	{
		id: 'protein-4',
		name: 'Suya',
		category: 'proteins',
		image: '/images/suya.png',
		price: 3000,
		description: 'Spicy grilled meat skewers',
		contents: [
			'Beef Suya (10 sticks)',
			'Suya spice (Yaji)',
			'Onions',
			'Cabbage',
			'Tomatoes',
		],
	},
	{
		id: 'protein-5',
		name: 'Goat Meat',
		category: 'proteins',
		image: '/images/goat-meat.jpg',
		price: 4000,
		description: 'Tender and flavorful goat meat',
		contents: ['Goat Meat', 'Pepper Sauce', 'Onions', 'Stock'],
	},
	{
		id: 'protein-6',
		name: 'Turkey',
		category: 'proteins',
		image: '/images/turkey.jpg',
		price: 6000,
		description: 'Juicy grilled turkey',
		contents: ['Whole Turkey (quarter)', 'Pepper Sauce', 'Onions', 'Spice rub'],
	},
	{
		id: 'protein-7',
		name: 'Fried Chicken',
		category: 'proteins',
		image: '/images/fried-chicken.jpg',
		price: 4000,
		description: 'Crispy fried chicken pieces',
		contents: ['Fried Chicken (6 pieces)', 'Ketchup', 'Coleslaw'],
	},
	{
		id: 'protein-8',
		name: 'Peppered Fish',
		category: 'proteins',
		image: '/images/peppered-fish.jpg',
		price: 4500,
		description: 'Fish in spicy pepper sauce',
		contents: [
			'Whole Fish',
			'Pepper Sauce',
			'Onions',
			'Tatashe peppers',
			'Spices',
		],
	},
	{
		id: 'protein-9',
		name: 'Asun',
		category: 'proteins',
		image: '/images/asun.jpg',
		price: 5000,
		description: 'Spicy grilled goat meat with peppers and onions',
		contents: [
			'Grilled Goat Meat',
			'Bell Peppers',
			'Onions',
			'Scotch bonnet',
			'Spices',
		],
	},
	{
		id: 'protein-10',
		name: 'Nkwobi',
		category: 'proteins',
		image: '/images/nkwobi.jpg',
		price: 5500,
		description: 'Spicy cow foot in thick palm oil sauce',
		contents: [
			'Cow Foot',
			'Palm Oil',
			'Ugba',
			'Crayfish',
			'Edible chalk (Nzu)',
			'Utazi leaves',
		],
	},
	{
		id: 'protein-11',
		name: 'Isi Ewu',
		category: 'proteins',
		image: '/images/isi-ewu.jpg',
		price: 7000,
		description: 'Spicy goat head delicacy',
		contents: [
			'Goat Head',
			'Palm Oil',
			'Ugba',
			'Crayfish',
			'Edible chalk (Nzu)',
			'Utazi leaves',
			'Pepper',
		],
	},
	{
		id: 'protein-12',
		name: 'Prawns',
		category: 'proteins',
		image: '/images/prawns.jpg',
		price: 8500,
		description:
			'Succulent prawns, lightly seasoned and cooked to perfection for a rich, savory taste',
		contents: ['Fresh Prawns', 'Garlic', 'Butter', 'Lemon', 'Spices'],
	},
	{
		id: 'protein-13',
		name: 'Turkey Wings',
		category: 'proteins',
		image: '/images/turkey-wings.jpg',
		price: 7500,
		description:
			'Juicy turkey wings marinated and grilled for a smoky, hearty flavor',
		contents: ['Turkey Wings', 'Marinade spices', 'Pepper Sauce', 'Onions'],
	},
	{
		id: 'protein-14',
		name: 'Spicy Pepper Chicken',
		category: 'proteins',
		image: '/images/pepper-chicken.jpg',
		price: 5500,
		description:
			'Spicy pepper chicken or smoky BBQ chicken, packed with bold, mouthwatering flavors',
		contents: [
			'Chicken pieces',
			'Pepper Sauce',
			'Scotch bonnet',
			'Onions',
			'Spices',
		],
	},
	{
		id: 'protein-15',
		name: 'Croaker Fish',
		category: 'proteins',
		image: '/images/croaker-fish.jpg',
		price: 5500,
		description:
			'Fresh croaker fish, delicately seasoned and either grilled or fried for a wholesome taste',
		contents: [
			'Whole Croaker Fish',
			'Pepper Sauce',
			'Lemon',
			'Onions',
			'Seasoning',
		],
	},
	{
		id: 'protein-16',
		name: 'Beef Kebab',
		category: 'proteins',
		image: '/images/beef-kebab.jpg',
		price: 4000,
		description:
			'Skewered beef chunks, marinated with spices and char-grilled to tender perfection',
		contents: [
			'Beef Chunks',
			'Kebab spices',
			'Onions',
			'Bell Peppers',
			'Tomatoes',
		],
	},
	{
		id: 'protein-17',
		name: 'Sausage',
		category: 'proteins',
		image: '/images/sausage.jpg',
		price: 2500,
		description:
			'Savory sausages grilled or pan-fried, adding a smoky, meaty delight to the plate',
		contents: ['Grilled Sausages', 'Onions', 'Pepper Sauce', 'Tomatoes'],
	},

	// Small Chops & Sides
	{
		id: 'side-1',
		name: 'Coleslaw',
		category: 'small-chops-sides',
		image: '/images/coleslaw.png',
		price: 1000,
		description: 'Crisp and refreshing coleslaw',
		contents: ['Cabbage', 'Carrots', 'Mayonnaise', 'Sweet corn', 'Sugar'],
	},
	{
		id: 'side-2',
		name: 'Plantain',
		category: 'small-chops-sides',
		image: '/images/plantain.png',
		price: 1500,
		description: 'Golden fried plantains',
		contents: ['Ripe Plantain (10 pieces)', 'Vegetable oil', 'Salt'],
	},
	{
		id: 'side-3',
		name: 'Yam',
		category: 'small-chops-sides',
		image: '/images/fried-yam.png',
		price: 1800,
		description: 'Perfectly fried yam chips',
		contents: [
			'Yam (10 pieces)',
			'Vegetable oil',
			'Salt',
			'Pepper sauce on the side',
		],
	},
	{
		id: 'side-4',
		name: 'Beans',
		category: 'small-chops-sides',
		image: '/images/beans.png',
		price: 1200,
		description: 'Cooked beans with seasoning',
		contents: ['Honey Beans', 'Pepper', 'Onions', 'Crayfish', 'Palm Oil'],
	},
	{
		id: 'side-5',
		name: 'Moin Moin',
		category: 'small-chops-sides',
		image: '/images/moin-moin.png',
		price: 1000,
		description: 'Steamed bean pudding',
		contents: [
			'Peeled Beans',
			'Bell Peppers',
			'Onions',
			'Crayfish',
			'Egg (optional)',
			'Fish (optional)',
		],
	},
	{
		id: 'side-6',
		name: 'Samosa',
		category: 'small-chops-sides',
		image: '/images/samosa.png',
		price: 800,
		description: 'Crispy pastry filled with spiced meat',
		contents: [
			'Samosa pastry',
			'Minced meat',
			'Onions',
			'Pepper',
			'Spices (4 pieces)',
		],
	},
	{
		id: 'side-7',
		name: 'Spring Rolls',
		category: 'small-chops-sides',
		image: '/images/spring-rolls.png',
		price: 800,
		description: 'Crispy vegetable spring rolls',
		contents: [
			'Spring roll pastry',
			'Cabbage',
			'Carrots',
			'Green beans',
			'Noodles (4 pieces)',
		],
	},
	{
		id: 'side-8',
		name: 'Puff Puff',
		category: 'small-chops-sides',
		image: '/images/puff-puff.jpg',
		price: 500,
		description: 'Sweet and fluffy deep-fried dough balls',
		contents: ['Flour dough', 'Sugar', 'Nutmeg', 'Yeast (6 pieces)'],
	},
	{
		id: 'side-9',
		name: 'Chicken Pie',
		category: 'small-chops-sides',
		image: '/images/chicken-pie.jpg',
		price: 800,
		description: 'Flaky pastry filled with chicken and vegetables',
		contents: [
			'Pie pastry',
			'Chicken',
			'Carrots',
			'Potatoes',
			'Peas',
			'Onions (1 piece)',
		],
	},
	{
		id: 'side-10',
		name: 'Meat Pie',
		category: 'small-chops-sides',
		image: '/images/meat-pie.jpg',
		price: 800,
		description: 'Classic Nigerian meat pie with minced meat filling',
		contents: [
			'Pie pastry',
			'Minced meat',
			'Carrots',
			'Potatoes',
			'Peas',
			'Onions (1 piece)',
		],
	},
	{
		id: 'side-11',
		name: 'Fish Roll',
		category: 'small-chops-sides',
		image: '/images/fish-roll.jpg',
		price: 700,
		description: 'Crispy pastry filled with spiced fish',
		contents: [
			'Pastry',
			'Mackerel fish',
			'Onions',
			'Pepper',
			'Spices (2 pieces)',
		],
	},
	{
		id: 'side-12',
		name: 'Yam Fries',
		category: 'small-chops-sides',
		image: '/images/yam-fries.jpg',
		price: 4000,
		description:
			'Crispy fried yam sticks served golden and delicious, perfect as a hearty side',
		contents: ['Yam', 'Vegetable oil', 'Salt', 'Seasoning', 'Pepper sauce'],
	},
	{
		id: 'side-13',
		name: 'French Fries',
		category: 'small-chops-sides',
		image: '/images/french-fries.jpg',
		price: 3000,
		description:
			'Classic golden French fries, crisp on the outside and fluffy inside',
		contents: ['Irish Potatoes', 'Vegetable oil', 'Salt', 'Seasoning'],
	},
	{
		id: 'side-14',
		name: 'Potato Fries',
		category: 'small-chops-sides',
		image: '/images/potato-fries.jpg',
		price: 3000,
		description:
			'Thick-cut potato fries fried to a golden crisp, hearty and satisfying',
		contents: [
			'Irish Potatoes',
			'Vegetable oil',
			'Salt',
			'Spices',
			'Pepper sauce',
		],
	},
	{
		id: 'side-15',
		name: 'Fried Plantain',
		category: 'small-chops-sides',
		image: '/images/fried-plantain.jpg',
		price: 2500,
		description:
			'Sweet ripe plantains sliced and fried golden brown, with a soft, caramelized taste',
		contents: ['Ripe Plantain', 'Vegetable oil', 'Salt'],
	},
	{
		id: 'side-16',
		name: 'Salad Dressing',
		category: 'small-chops-sides',
		image: '/images/salad-dressing.jpg',
		price: 2500,
		description:
			'Creamy or tangy dressing to complement fresh greens and sides',
		contents: ['Mayonnaise base', 'Vinegar', 'Herbs', 'Spices'],
	},
	{
		id: 'side-17',
		name: 'Fried Potato',
		category: 'small-chops-sides',
		image: '/images/fried-potato.jpg',
		price: 1500,
		description: 'Crispy fried potato wedges',
		contents: [
			'Irish potatoes',
			'Vegetable oil',
			'Salt',
			'Seasoning',
			'Pepper sauce',
		],
	},

	// Pasta
	{
		id: 'pasta-1',
		name: 'Penne Royale',
		category: 'pasta',
		image: '/images/penne-royale.jpg',
		price: 23500,
		description:
			'Penne pasta cooked in a creamy sauce infused with chicken chunks and prawns',
		contents: [
			'Penne Pasta',
			'Chicken chunks',
			'Prawns',
			'Cream sauce',
			'Vegetables',
			'Parmesan cheese',
		],
	},
	{
		id: 'pasta-2',
		name: 'Singapore Noodles',
		category: 'pasta',
		image: '/images/singapore-noodles.jpg',
		price: 19500,
		description: 'Singapore noodles with chicken strips and prawns',
		contents: [
			'Egg Noodles',
			'Chicken strips',
			'Prawns',
			'Curry sauce',
			'Vegetables',
			'Sesame oil',
		],
	},
	{
		id: 'pasta-3',
		name: 'Spaghetti Stir-Fry Delight',
		category: 'pasta',
		image: '/images/spaghetti-stir-fry.jpg',
		price: 15250,
		description:
			'Spaghetti stir fry in rich pepper and Chinese sauces infused with chicken/beef strips served with peppered chicken',
		contents: [
			'Spaghetti',
			'Chicken/Beef strips',
			'Bell Peppers',
			'Onions',
			'Chinese sauce',
			'Peppered Chicken',
		],
	},
	{
		id: 'pasta-4',
		name: 'Spaghetti Stir Fry',
		category: 'pasta',
		image: '/images/spaghetti-stir-fry-basic.jpg',
		price: 9500,
		description:
			'Special Spaghetti stir fry with chicken and beef strips in Chinese sauce',
		contents: [
			'Spaghetti',
			'Chicken strips',
			'Beef strips',
			'Chinese sauce',
			'Vegetables',
			'Sesame oil',
		],
	},

	// Combo Menu
	{
		id: 'combo-1',
		name: 'King Combo',
		category: 'combo-menu',
		image: '/images/king-combo.png',
		price: 8500,
		description: 'Rice, proteins, soup and sides - the ultimate meal',
		contents: [
			'Jollof Rice',
			'Grilled Chicken',
			'Moin Moin',
			'Coleslaw',
			'Plantain',
			'Drink (35cl)',
		],
	},
	{
		id: 'combo-2',
		name: 'Classic Combo',
		category: 'combo-menu',
		image: '/images/classic-combo.png',
		price: 6500,
		description: 'Swallow with soup and meat',
		contents: [
			'Amala/Eba/Semovita',
			'Egusi/Ogbono Soup',
			'Beef',
			'Fish',
			'Drink (35cl)',
		],
	},
	{
		id: 'combo-3',
		name: 'Family Combo',
		category: 'combo-menu',
		image: '/images/family-combo.png',
		price: 12000,
		description: 'Complete meal for the whole family (serves 3-4)',
		contents: [
			'Jollof Rice (large)',
			'Fried Rice (large)',
			'Grilled Chicken (whole)',
			'Moin Moin (4 pieces)',
			'Coleslaw (medium)',
			'Plantain (12 pieces)',
			'Drinks (4 bottles)',
		],
	},
	{
		id: 'combo-4',
		name: 'Budget Combo',
		category: 'combo-menu',
		image: '/images/budget-combo.png',
		price: 4500,
		description: 'Affordable yet satisfying combo',
		contents: [
			'Jollof Rice/Fried Rice',
			'Beef',
			'Moin Moin',
			'Plantain',
			'Drink (35cl)',
		],
	},
	{
		id: 'combo-5',
		name: 'Date Night Combo',
		category: 'combo-menu',
		image: '/images/date-combo.jpg',
		price: 9500,
		description: 'Perfect for two - includes drinks and small chops',
		contents: [
			'Jollof Rice (2 servings)',
			'Fried Rice (2 servings)',
			'Grilled Chicken (2 pieces)',
			'Small Chops assortment',
			'Chapman (2 glasses)',
			'Coke (2 bottles)',
		],
	},
	{
		id: 'combo-6',
		name: 'Protein Lover Combo',
		category: 'combo-menu',
		image: '/images/protein-combo.jpg',
		price: 7800,
		description: 'Double protein portion with rice and sides',
		contents: [
			'Jollof Rice',
			'Fried Rice',
			'Grilled Chicken',
			'Goat Meat',
			'Fish',
			'Coleslaw',
			'Plantain',
		],
	},
	{
		id: 'combo-7',
		name: 'Special Prawn Fried Rice',
		category: 'combo-menu',
		image: '/images/prawn-fried-rice.jpg',
		price: 23500,
		description:
			'Basmati fried rice with prawns/shrimps, chicken/beef bites paired with fried plantain and peppered Chicken',
		contents: [
			'Basmati Fried Rice',
			'Prawns/Shrimps',
			'Chicken/Beef bites',
			'Fried Plantain',
			'Peppered Chicken',
			'Vegetables',
		],
	},
	{
		id: 'combo-8',
		name: 'Jambalaya Rice with Chicken',
		category: 'combo-menu',
		image: '/images/jambalaya.jpg',
		price: 22900,
		description:
			'A vibrant mix of prawns, shrimps, juicy sausages, and crispy fried hake fish, all folded into seasoned rice slow-cooked in a rich, savoury tomato and bell pepper sauce paired with fried plantain and peppered Chicken',
		contents: [
			'Basmati Rice',
			'Prawns',
			'Shrimps',
			'Sausages',
			'Fried Hake Fish',
			'Tomato sauce',
			'Fried Plantain',
			'Peppered Chicken',
		],
	},
	{
		id: 'combo-9',
		name: 'Rice Stew & Everything Nice',
		category: 'combo-menu',
		image: '/images/rice-stew-combo.jpg',
		price: 19500,
		description: 'Fresh tomato stew with fried plantain, chicken & Beef',
		contents: [
			'Rice',
			'Fresh Tomato Stew',
			'Chicken',
			'Beef',
			'Fried Plantain',
		],
	},
	{
		id: 'combo-10',
		name: 'Village Pot Rice with Chicken',
		category: 'combo-menu',
		image: '/images/village-pot-rice.jpg',
		price: 19200,
		description:
			'Native rice cooked in rich palm oil with local spices, ejakika, tender Dryfish, and succulent pomo served with plantain and peppered chicken',
		contents: [
			'Native Rice',
			'Palm Oil',
			'Local spices',
			'Ejakika',
			'Dryfish',
			'Pomo',
			'Plantain',
			'Peppered Chicken',
		],
	},
	{
		id: 'combo-11',
		name: 'Jollof Fiesta Combo',
		category: 'combo-menu',
		image: '/images/jollof-fiesta.jpg',
		price: 16750,
		description:
			'Smokey party jollof, paired with peppered chicken, plantain and coleslaw',
		contents: ['Jollof Rice', 'Peppered Chicken', 'Fried Plantain', 'Coleslaw'],
	},
	{
		id: 'combo-12',
		name: 'Special Basmati Prawn Fried Rice',
		category: 'combo-menu',
		image: '/images/basmati-prawn-rice.jpg',
		price: 14500,
		description:
			'Basmati rice stir fried with chicken and beef cubed with prawns and vegetables',
		contents: [
			'Basmati Rice',
			'Chicken cubes',
			'Beef cubes',
			'Prawns',
			'Mixed Vegetables',
			'Sesame oil',
		],
	},
	{
		id: 'combo-13',
		name: 'Village Pot Rice',
		category: 'combo-menu',
		image: '/images/village-pot-rice-basic.jpg',
		price: 10500,
		description:
			'Native rice cooked in rich palm oil with local spices, ejakika, tender Dryfish, and succulent pomo served with plantain',
		contents: [
			'Native Rice',
			'Palm Oil',
			'Local spices',
			'Ejakika',
			'Dryfish',
			'Pomo',
			'Plantain',
		],
	},

	// Breakfast Menu
	{
		id: 'breakfast-1',
		name: 'Pap & Akara',
		category: 'breakfast-menu',
		image: '/images/pap-and-akara.jpg',
		price: 1800,
		description: 'Fresh pap with bean cakes',
		contents: [
			'Pap (Fermented corn pudding)',
			'Akara (Bean cakes - 4 pieces)',
			'Sugar',
			'Milk',
			'Bread (optional)',
		],
	},
	{
		id: 'breakfast-2',
		name: 'Bread & Egg',
		category: 'breakfast-menu',
		image: '/images/bread-and-egg.png',
		price: 1500,
		description: 'Fresh bread with fried eggs',
		contents: [
			'Agege Bread (half loaf)',
			'Fried Eggs (2 pieces)',
			'Butter',
			'Beverage (tea/coffee)',
		],
	},
	{
		id: 'breakfast-3',
		name: 'Oatmeal',
		category: 'breakfast-menu',
		image: '/images/oatmeal.jfif',
		price: 2000,
		description: 'Creamy oatmeal with fruits',
		contents: [
			'A plate of Oatmeal with a slice of Banana and dip of Honey, Tin of Milk and Sugar on the side',
		],
	},
	{
		id: 'breakfast-4',
		name: 'Breakfast Platter',
		category: 'breakfast-menu',
		image: '/images/breakfast.webp',
		price: 3500,
		description: 'Tea, bread, Egg, fruits and more',
		contents: [
			'Scrambled Eggs (2)',
			'Sausages (2)',
			'Baked Beans',
			'Toast Bread (2 slices)',
			'Fresh Fruits',
			'Tea/Coffee',
		],
	},
	{
		id: 'breakfast-5',
		name: 'Yam & Egg',
		category: 'breakfast-menu',
		image: '/images/yam-and-egg.jpeg',
		price: 2500,
		description: 'Fried yam with scrambled eggs',
		contents: [
			'Fried Yam (8 pieces)',
			'Scrambled Eggs (2)',
			'Pepper Sauce',
			'Vegetable Oil',
			'Onions',
		],
	},
	{
		id: 'breakfast-6',
		name: 'Pancakes',
		category: 'breakfast-menu',
		image: '/images/pancakes.png',
		price: 2000,
		description: 'Fluffy pancakes with syrup',
		contents: ['Pancakes (4 pieces)', 'Maple Syrup', 'Butter', 'Fresh Fruits'],
	},
	{
		id: 'breakfast-7',
		name: 'French Toast',
		category: 'breakfast-menu',
		image: '/images/french-toast.jpg',
		price: 2200,
		description: 'Bread dipped in egg mixture and fried golden brown',
		contents: [
			'French Toast (4 slices)',
			'Maple Syrup',
			'Butter',
			'Cinnamon',
			'Fresh Fruits',
		],
	},
	{
		id: 'breakfast-8',
		name: 'Akara & Bread',
		category: 'breakfast-menu',
		image: '/images/akara-bread.jpg',
		price: 1800,
		description: 'Fresh bean cakes with agege bread',
		contents: [
			'Akara (6 pieces)',
			'Agege Bread (half loaf)',
			'Pepper Sauce',
			'Pap (optional)',
		],
	},
	{
		id: 'breakfast-9',
		name: 'Moi Moi & Bread',
		category: 'breakfast-menu',
		image: '/images/moi-moi-bread.jpg',
		price: 2000,
		description: 'Steamed bean pudding with fresh bread',
		contents: [
			'Moin Moin (2 wraps)',
			'Agege Bread (half loaf)',
			'Beverage (tea/coffee)',
		],
	},
	{
		id: 'breakfast-10',
		name: 'Tea & Bread',
		category: 'breakfast-menu',
		image: '/images/tea-bread.jpg',
		price: 1200,
		description: 'Hot tea with fresh bread',
		contents: [
			'Tea (Milo/Lipton)',
			'Agege Bread (half loaf)',
			'Butter',
			'Milk',
			'Sugar',
		],
	},
	{
		id: 'breakfast-11',
		name: 'Coffee & Bread',
		category: 'breakfast-menu',
		image: '/images/coffee-bread.jpg',
		price: 1500,
		description: 'Fresh brewed coffee with bread',
		contents: [
			'Fresh Brewed Coffee',
			'Agege Bread (half loaf)',
			'Butter',
			'Sugar',
		],
	},
	{
		id: 'breakfast-12',
		name: 'Double the Fun Platter',
		category: 'breakfast-menu',
		image: '/images/double-fun-platter.jpg',
		price: 37900,
		description:
			'Yam fried, sweet potato fried, plantain fries, turkey and bbq chicken (Feeds 2)',
		contents: [
			'Fried Yam',
			'Fried Sweet Potato',
			'Plantain Fries',
			'Turkey',
			'BBQ Chicken',
		],
	},
	{
		id: 'breakfast-13',
		name: 'Crispy Chicken Pancake Delight',
		category: 'breakfast-menu',
		image: '/images/chicken-pancake.jpg',
		price: 15500,
		description:
			'Buttermilk pancakes, chicken tenders, sausages, scrambled eggs, dipping sauce and syrup',
		contents: [
			'Buttermilk Pancakes',
			'Chicken Tenders',
			'Sausages',
			'Scrambled Eggs',
			'Dipping Sauce',
			'Maple Syrup',
		],
	},
	{
		id: 'breakfast-14',
		name: 'Waffle Delight',
		category: 'breakfast-menu',
		image: '/images/waffle-delight.jpg',
		price: 18500,
		description:
			'Chocolate and buttermilk waffles with crispy buttermilk pancakes, chicken tenders, sausages, scrambled eggs, dipping sauce and syrup',
		contents: [
			'Chocolate Waffles',
			'Buttermilk Waffles',
			'Buttermilk Pancakes',
			'Chicken Tenders',
			'Sausages',
			'Scrambled Eggs',
			'Dipping Sauce',
			'Maple Syrup',
		],
	},
	{
		id: 'breakfast-15',
		name: 'Stir Fry Noodles',
		category: 'breakfast-menu',
		image: '/images/breakfast-stir-fry.jpg',
		price: 14500,
		description:
			'Wok stir fried noodles with chicken/beef, omelette and sausages',
		contents: [
			'Egg Noodles',
			'Chicken/Beef',
			'Omelette',
			'Sausages',
			'Vegetables',
			'Sesame oil',
		],
	},

	// Drinks
	{
		id: 'drink-1',
		name: 'Coca Cola',
		category: 'drinks',
		image: '/images/coke.jpg',
		price: 300,
		description: 'Ice-cold Coca Cola (35cl)',
		contents: ['Coca Cola (35cl bottle)', 'Ice (optional)'],
	},
	{
		id: 'drink-2',
		name: 'Fanta',
		category: 'drinks',
		image: '/images/fanta.jpg',
		price: 300,
		description: 'Ice-cold Fanta (35cl)',
		contents: ['Fanta (35cl bottle)', 'Ice (optional)'],
	},
	{
		id: 'drink-3',
		name: 'Sprite',
		category: 'drinks',
		image: '/images/sprite.jpg',
		price: 300,
		description: 'Ice-cold Sprite (35cl)',
		contents: ['Sprite (35cl bottle)', 'Ice (optional)'],
	},
	{
		id: 'drink-4',
		name: 'Malta Guinness',
		category: 'drinks',
		image: '/images/malta.jpg',
		price: 400,
		description: 'Rich non-alcoholic malt drink',
		contents: ['Malta Guinness (40cl bottle)', 'Ice (optional)'],
	},
	{
		id: 'drink-5',
		name: 'Zobo Drink',
		category: 'drinks',
		image: '/images/zobo.jpg',
		price: 500,
		description: 'Refreshing hibiscus drink with ginger and pineapple',
		contents: [
			'Hibiscus extract',
			'Ginger',
			'Pineapple',
			'Cloves',
			'Sugar (500ml bottle)',
		],
	},
	{
		id: 'drink-6',
		name: 'Chapman',
		category: 'drinks',
		image: '/images/chapman.jpg',
		price: 800,
		description: 'Classic Nigerian cocktail - non-alcoholic',
		contents: [
			'Fanta',
			'Sprite',
			'Angostura bitters',
			'Grenadine',
			'Lemon',
			'Cucumber (500ml)',
		],
	},
	{
		id: 'drink-7',
		name: 'Fruit Juice',
		category: 'drinks',
		image: '/images/fruit-juice.jpg',
		price: 600,
		description: 'Freshly squeezed orange juice',
		contents: ['Fresh Oranges (500ml)', 'Ice (optional)'],
	},
	{
		id: 'drink-8',
		name: 'Kunu',
		category: 'drinks',
		image: '/images/kunu.jpg',
		price: 400,
		description: 'Traditional millet drink',
		contents: ['Millet', 'Ginger', 'Cloves', 'Sugar (500ml bottle)'],
	},
	{
		id: 'drink-9',
		name: 'Sobo',
		category: 'drinks',
		image: '/images/sobo.jpg',
		price: 400,
		description: 'Refreshing hibiscus drink',
		contents: ['Hibiscus', 'Ginger', 'Cloves', 'Sugar (500ml bottle)'],
	},
	{
		id: 'drink-10',
		name: 'Energy Drink',
		category: 'drinks',
		image: '/images/energy-drink.jpg',
		price: 500,
		description: 'Energy boost drink',
		contents: ['Energy drink (Fearless/Predator)', 'Ice (optional)'],
	},
	{
		id: 'drink-11',
		name: 'Bottled Water',
		category: 'drinks',
		image: '/images/water.jpg',
		price: 200,
		description: 'Pure bottled water (75cl)',
		contents: ['Pure Water (75cl bottle)'],
	},
	{
		id: 'drink-12',
		name: 'Hollandia Yogurt',
		category: 'drinks',
		image: '/images/yogurt.jpg',
		price: 600,
		description: 'Creamy yogurt drink',
		contents: ['Hollandia Yogurt (500ml bottle)'],
	},

	// Fast Food
	{
		id: 'fastfood-1',
		name: 'Chicken Pizza',
		category: 'fast-food',
		image: '/images/chicken-pizza.jpg',
		price: 6500,
		description: 'Large pizza with grilled chicken and vegetables',
		contents: [
			'Pizza dough',
			'Grilled Chicken',
			'Mozzarella Cheese',
			'Bell Peppers',
			'Onions',
			'Tomato sauce (Large - 12 inches)',
		],
	},
	{
		id: 'fastfood-2',
		name: 'Beef Pizza',
		category: 'fast-food',
		image: '/images/beef-pizza.jpg',
		price: 6000,
		description: 'Large pizza with seasoned beef and cheese',
		contents: [
			'Pizza dough',
			'Seasoned Beef',
			'Mozzarella Cheese',
			'Bell Peppers',
			'Onions',
			'Mushrooms (Large - 12 inches)',
		],
	},
	{
		id: 'fastfood-3',
		name: 'Shawarma',
		category: 'fast-food',
		image: '/images/shawarma.jpg',
		price: 3500,
		description: 'Chicken shawarma with garlic sauce and vegetables',
		contents: [
			'Shawarma bread',
			'Grilled Chicken',
			'Garlic sauce',
			'Cabbage',
			'Carrots',
			'Cucumber',
			'Mayonnaise (1 wrap)',
		],
	},
	{
		id: 'fastfood-4',
		name: 'Beef Shawarma',
		category: 'fast-food',
		image: '/images/beef-shawarma.jpg',
		price: 3800,
		description: 'Beef shawarma with special sauce',
		contents: [
			'Shawarma bread',
			'Seasoned Beef',
			'Garlic sauce',
			'Cabbage',
			'Carrots',
			'Cucumber',
			'Mayonnaise (1 wrap)',
		],
	},
	{
		id: 'fastfood-5',
		name: 'Chicken Burger',
		category: 'fast-food',
		image: '/images/chicken-burger.jpg',
		price: 3200,
		description: 'Grilled chicken burger with lettuce and mayo',
		contents: [
			'Burger bun',
			'Grilled Chicken patty',
			'Lettuce',
			'Tomatoes',
			'Onions',
			'Cheese',
			'Mayonnaise',
		],
	},
	{
		id: 'fastfood-6',
		name: 'Beef Burger',
		category: 'fast-food',
		image: '/images/beef-burger.jpg',
		price: 3000,
		description: 'Juicy beef burger with cheese and vegetables',
		contents: [
			'Burger bun',
			'Beef patty',
			'Lettuce',
			'Tomatoes',
			'Onions',
			'Cheese',
			'Ketchup',
		],
	},
	{
		id: 'fastfood-7',
		name: 'French Fries',
		category: 'fast-food',
		image: '/images/fries.jpg',
		price: 1800,
		description: 'Crispy golden french fries',
		contents: ['Potatoes', 'Salt', 'Ketchup (medium portion)'],
	},
	{
		id: 'fastfood-8',
		name: 'Chicken Wings',
		category: 'fast-food',
		image: '/images/chicken-wings.jpg',
		price: 3500,
		description: 'Spicy fried chicken wings (6 pieces)',
		contents: [
			'Chicken wings (6 pieces)',
			'Spicy batter',
			'Ketchup',
			'BBQ sauce (optional)',
		],
	},
	{
		id: 'fastfood-9',
		name: 'Hot Dog',
		category: 'fast-food',
		image: '/images/hotdog.jpg',
		price: 2500,
		description: 'Grilled sausage in a bun with toppings',
		contents: [
			'Hot dog bun',
			'Beef sausage',
			'Ketchup',
			'Mustard',
			'Mayonnaise',
			'Fried onions',
		],
	},
	{
		id: 'fastfood-10',
		name: 'Onion Rings',
		category: 'fast-food',
		image: '/images/onion-rings.jpg',
		price: 1500,
		description: 'Crispy battered onion rings',
		contents: ['Onion rings (8 pieces)', 'Batter', 'Ketchup', 'BBQ sauce'],
	},
	{
		id: 'fastfood-11',
		name: 'Chicken Strips',
		category: 'fast-food',
		image: '/images/chicken-strips.jpg',
		price: 2800,
		description: 'Crispy chicken strips with dipping sauce',
		contents: [
			'Chicken strips (5 pieces)',
			'Breading',
			'Ketchup',
			'Honey mustard sauce',
			'French fries (side)',
		],
	},
];
